Traceback (most recent call last):
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mike/Projects/python/venvs/jbook/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import urllib.request
url="https://raw.githubusercontent.com/drmikecooke/drmikecooke.github.io/1aede484156466d380ce33480e6fc7979a3da1e3/ST/json/ST-update.py"
a = urllib.request.urlopen(url)
code=a.read()
print(code.decode("utf8"))
exec(code)
------------------

----- stdout -----
import json

def get(file):
    with open(file, 'r') as fp:
        return json.load(fp)

def put(d,file):
    with open(file, 'w') as fp:
        json.dump(d, fp)

def STitem(caption,img,url,ref):
    return {'caption':caption,'img':img,'url':url,'ref':ref}

def addSTitem(d,month,item):
    if month in d.keys():
        d[month] += [item]
    else:
        d = {month:[item],**d}
    return d

def inputST(d):
    month=input('Month: ')
    caption=input('Caption: ')
    img=input('Image: ')
    href=input('Link: ')
    ref=input('Reference: ')
    return addSTitem(d,month,STitem(caption,img,href,ref))

if __name__ == "__main__":
	j=get('2023.json')
	put(j,'2023.json.bak')
	j=inputST(j)
	put(j,'2023.json')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 6[0m
[1;32m      4[0m code[38;5;241m=[39ma[38;5;241m.[39mread()
[1;32m      5[0m [38;5;28mprint[39m(code[38;5;241m.[39mdecode([38;5;124m"[39m[38;5;124mutf8[39m[38;5;124m"[39m))
[0;32m----> 6[0m [43mexec[49m[43m([49m[43mcode[49m[43m)[49m

File [0;32m<string>:30[0m

File [0;32m<string>:4[0m, in [0;36mget[0;34m(file)[0m

File [0;32m~/Projects/python/venvs/jbook/lib/python3.9/site-packages/IPython/core/interactiveshell.py:310[0m, in [0;36m_modified_open[0;34m(file, *args, **kwargs)[0m
[1;32m    303[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[1;32m    304[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    305[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[1;32m    306[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[1;32m    307[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[1;32m    308[0m     )
[0;32m--> 310[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '2023.json'

